FROM node:12.18.0

WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY . .

## install only the packages defined in the package-lock.json (faster than the normal npm install)
RUN npm ci


# Run 'npm start' when the container starts.
CMD ["npm", "run", "start"]