# Specify a base image
FROM node:12.18.0

# This folder will be created inside of the container
WORKDIR /app 

# Install dependencies
# COPY will be executed on the HOST machine
COPY . .

RUN npm ci


# Default command, executes them in the container
CMD ["npm", "run", "dev"]